# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: Copyright © the xdg-desktop-portal contributors

context.properties = {
    # Disable first-party portal module to be replaced with xdg-desktop-portal
    # own module
    module.portal = false
}

context.modules = [
    { name = libxdg-desktop-portal
        flags = [ ifexists ]
        condition = [ { module.xdp-desktop-portal = !false } ]
    }
]
