#!/usr/bin/env bash
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
CHECK_TEST_PYTHON="${HERE}/check-tests-python.sh"

path_unchanged()
{
  ! git diff --cached --name-only | grep $1 >/dev/null
}

check()
{
  if [ -z ${PRE_COMMIT_STASH+x} ]; then
    PRE_COMMIT_STASH=1

    clean_up ()
    {
      git stash pop -q
    }

    if ! git diff -s --exit-code; then
      git stash push -q --keep-index
      trap clean_up EXIT
    fi
  fi

  $@
}

path_unchanged ^tests/ || check $CHECK_TEST_PYTHON || CHECK_FAILED=1

[ -z ${CHECK_FAILED+x} ] || exit 1
