# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: Copyright © the xdg-desktop-portal contributors

min_glib_version = "2.76"
ignore = [
  "subprojects/**",
  "document-portal/gvdb/**",
  "pipewire/pw-module/**",
]
default_level = "error"

[rules.type_style]
level = "ignore"