#!/usr/bin/env bash
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText:

set -eo pipefail

IMAGE=xdg-desktop-portal-check:latest

PREFIX="${TOOLBOX_PATH:+flatpak-spawn --host}"
CMD="${PREFIX} $(${PREFIX} sh -c 'command -v podman docker')"

$CMD build -f containerfiles/check.containerfile -t "${IMAGE}" .
