/* SPDX-License-Identifier: LGPL-2.1-or-later
 * SPDX-FileCopyrightText: Copyright © the xdg-desktop-portal contributors
 */

#pragma once

#include <gio/gio.h>

#include "xdp-session.h"
#include "xdp-types.h"

typedef struct _RemoteDesktopSession RemoteDesktopSession;

/* This should be generated by G_DECLARE_FINAL_TYPE but we can't use it here
 * because it has no xdp prefix.
 * gobject-linter-ignore-next-line: missing_implementation */
GType remote_desktop_session_get_type (void);

G_GNUC_UNUSED static inline RemoteDesktopSession *
REMOTE_DESKTOP_SESSION (gpointer ptr)
{
  return G_TYPE_CHECK_INSTANCE_CAST (ptr, remote_desktop_session_get_type (), RemoteDesktopSession);
}

G_GNUC_UNUSED static inline gboolean
IS_REMOTE_DESKTOP_SESSION (gpointer ptr)
{
  return G_TYPE_CHECK_INSTANCE_TYPE (ptr, remote_desktop_session_get_type ());
}

GList * remote_desktop_session_get_streams (RemoteDesktopSession *session);

gboolean remote_desktop_session_can_select_sources (RemoteDesktopSession *session);

gboolean remote_desktop_session_can_request_clipboard (RemoteDesktopSession *session);

gboolean remote_desktop_session_is_clipboard_enabled (RemoteDesktopSession *session);

void remote_desktop_session_sources_selected (RemoteDesktopSession *session);

void remote_desktop_session_clipboard_requested (RemoteDesktopSession *session);

gboolean
remote_desktop_session_can_access_clipboard (RemoteDesktopSession *session);

void init_remote_desktop (XdpContext *context);
