# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: Copyright © the xdg-desktop-portal contributors

blank_issues_enabled: false
contact_links:
  - name: Help/Support
    url: https://matrix.to/#/#xdg-desktop-portals:matrix.org
    about: Questions or issues about how to use and configure xdg-desktop-portal
