introspectiondir = $(datadir)/dbus-1/interfaces
dist_introspection_DATA = \
	data/org.freedesktop.portal.Documents.xml \
	data/org.freedesktop.portal.Request.xml \
	data/org.freedesktop.portal.Session.xml \
	data/org.freedesktop.portal.FileChooser.xml \
	data/org.freedesktop.portal.Trash.xml \
	data/org.freedesktop.portal.OpenURI.xml \
	data/org.freedesktop.portal.Print.xml \
	data/org.freedesktop.portal.NetworkMonitor.xml \
	data/org.freedesktop.portal.ProxyResolver.xml \
	data/org.freedesktop.portal.Screenshot.xml \
	data/org.freedesktop.portal.Notification.xml \
	data/org.freedesktop.portal.Inhibit.xml \
	data/org.freedesktop.portal.Device.xml \
	data/org.freedesktop.portal.Account.xml \
	data/org.freedesktop.portal.Email.xml \
	data/org.freedesktop.portal.ScreenCast.xml \
	data/org.freedesktop.portal.RemoteDesktop.xml \
	data/org.freedesktop.portal.Location.xml \
	data/org.freedesktop.portal.Settings.xml \
	data/org.freedesktop.impl.portal.PermissionStore.xml \
	data/org.freedesktop.impl.portal.Request.xml \
	data/org.freedesktop.impl.portal.Session.xml \
	data/org.freedesktop.impl.portal.FileChooser.xml \
	data/org.freedesktop.impl.portal.AppChooser.xml \
	data/org.freedesktop.impl.portal.Print.xml \
	data/org.freedesktop.impl.portal.Screenshot.xml \
	data/org.freedesktop.impl.portal.Notification.xml \
	data/org.freedesktop.impl.portal.Inhibit.xml \
	data/org.freedesktop.impl.portal.Access.xml \
	data/org.freedesktop.impl.portal.Account.xml \
	data/org.freedesktop.impl.portal.Email.xml \
	data/org.freedesktop.impl.portal.ScreenCast.xml \
	data/org.freedesktop.impl.portal.RemoteDesktop.xml \
	data/org.freedesktop.impl.portal.Settings.xml \
	$(NULL)
