/* SPDX-License-Identifier: LGPL-2.1-or-later
 * SPDX-FileCopyrightText: Copyright © the xdg-desktop-portal contributors
 */

#pragma once

#include <gio/gio.h>

typedef enum {
  XDG_DESKTOP_PORTAL_RESPONSE_SUCCESS = 0,
  XDG_DESKTOP_PORTAL_RESPONSE_CANCELLED = 1,
  XDG_DESKTOP_PORTAL_RESPONSE_OTHER = 2,
} XdgDesktopPortalResponseEnum;

typedef enum _XdpEntitlement
{
  XDP_ENTITLEMENT_NONE = 0,
  XDP_ENTITLEMENT_ACCOUNT,
  XDP_ENTITLEMENT_BACKGROUND,
  XDP_ENTITLEMENT_CAMERA,
  XDP_ENTITLEMENT_CLIPBOARD,
  XDP_ENTITLEMENT_DYNAMIC_LAUNCHER,
  XDP_ENTITLEMENT_EMAIL,
  XDP_ENTITLEMENT_FILE_CHOOSER,
  XDP_ENTITLEMENT_GAMEMODE,
  XDP_ENTITLEMENT_GLOBAL_SHORTCUTS,
  XDP_ENTITLEMENT_INHIBIT,
  XDP_ENTITLEMENT_INPUT_CAPTURE,
  XDP_ENTITLEMENT_LOCATION,
  XDP_ENTITLEMENT_MEMORY_MONITOR,
  XDP_ENTITLEMENT_NETWORK_MONITOR,
  XDP_ENTITLEMENT_NOTIFICATION,
  XDP_ENTITLEMENT_OPEN_URI,
  XDP_ENTITLEMENT_POWER_PROFILE_MONITOR,
  XDP_ENTITLEMENT_PRINT,
  XDP_ENTITLEMENT_PROXY_RESOLVER,
  XDP_ENTITLEMENT_REALTIME,
  XDP_ENTITLEMENT_REMOTE_DESKTOP,
  XDP_ENTITLEMENT_SCREEN_CAST,
  XDP_ENTITLEMENT_SCREENSHOT,
  XDP_ENTITLEMENT_SECRET,
  XDP_ENTITLEMENT_SETTINGS,
  XDP_ENTITLEMENT_TRASH,
  XDP_ENTITLEMENT_USB,
  XDP_ENTITLEMENT_USB_DEVICES,
  XDP_ENTITLEMENT_WALLPAPER,
} XdpEntitlement;

typedef struct _XdpContext XdpContext;
typedef struct _XdpAppInfo XdpAppInfo;
typedef struct _XdpEntitlements XdpEntitlements;
typedef struct _XdpAppInfoRegistry XdpAppInfoRegistry;
typedef struct _XdpPortalConfig XdpPortalConfig;
typedef struct _XdpDbusImplLockdown XdpDbusImplLockdown;
typedef struct _XdpDbusImplAccess XdpDbusImplAccess;

#define XDG_PORTAL_APPLICATIONS_DIR "xdg-desktop-portal" G_DIR_SEPARATOR_S "applications"
#define XDG_PORTAL_ICONS_DIR "xdg-desktop-portal" G_DIR_SEPARATOR_S "icons"

#define DBUS_DBUS_NAME "org.freedesktop.DBus"
#define DBUS_DBUS_IFACE "org.freedesktop.DBus"
#define DBUS_DBUS_PATH "/org/freedesktop/DBus"

#define DESKTOP_DBUS_NAME "org.freedesktop.portal.Desktop"
#define DESKTOP_DBUS_IFACE "org.freedesktop.portal"
#define DESKTOP_DBUS_IMPL_IFACE "org.freedesktop.impl.portal"
#define DESKTOP_DBUS_PATH "/org/freedesktop/portal/desktop"

#define ACCESS_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Access"

#define LOCKDOWN_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Lockdown"

#define APP_CHOOSER_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".AppChooser"

#define ACCOUNT_DBUS_IFACE DESKTOP_DBUS_IFACE ".Account"
#define ACCOUNT_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Account"
#define ACCOUNT_ENTITLEMENT_NAME ACCOUNT_DBUS_IFACE

#define BACKGROUND_DBUS_IFACE DESKTOP_DBUS_IFACE ".Background"
#define BACKGROUND_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Background"
#define BACKGROUND_PERMISSION_TABLE "background"
#define BACKGROUND_PERMISSION_ID "background"
#define BACKGROUND_ENTITLEMENT_NAME BACKGROUND_DBUS_IFACE

#define CAMERA_DBUS_IFACE DESKTOP_DBUS_IFACE ".Camera"
#define CAMERA_PERMISSION_TABLE "devices"
#define CAMERA_PERMISSION_DEVICE_CAMERA "camera"
#define CAMERA_ENTITLEMENT_NAME CAMERA_DBUS_IFACE

#define CLIPBOARD_DBUS_IFACE DESKTOP_DBUS_IFACE ".Clipboard"
#define CLIPBOARD_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Clipboard"
#define CLIPBOARD_ENTITLEMENT_NAME CLIPBOARD_DBUS_IFACE

#define DYNAMIC_LAUNCHER_DBUS_IFACE DESKTOP_DBUS_IFACE ".DynamicLauncher"
#define DYNAMIC_LAUNCHER_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".DynamicLauncher"
#define DYNAMIC_LAUNCHER_ENTITLEMENT_NAME DYNAMIC_LAUNCHER_DBUS_IFACE

#define EMAIL_DBUS_IFACE DESKTOP_DBUS_IFACE ".Email"
#define EMAIL_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Email"
#define EMAIL_ENTITLEMENT_NAME EMAIL_DBUS_IFACE

#define FILE_CHOOSER_DBUS_IFACE DESKTOP_DBUS_IFACE ".FileChooser"
#define FILE_CHOOSER_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".FileChooser"
#define FILE_CHOOSER_ENTITLEMENT_NAME FILE_CHOOSER_DBUS_IFACE

#define GAMEMODE_DBUS_IFACE DESKTOP_DBUS_IFACE ".GameMode"
#define GAMEMODE_PERMISSION_TABLE "gamemode"
#define GAMEMODE_PERMISSION_ID "gamemode"
#define GAMEMODE_ENTITLEMENT_NAME GAMEMODE_DBUS_IFACE

#define GLOBAL_SHORTCUTS_DBUS_IFACE DESKTOP_DBUS_IFACE ".GlobalShortcuts"
#define GLOBAL_SHORTCUTS_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".GlobalShortcuts"
#define GLOBAL_SHORTCUTS_ENTITLEMENT_NAME GLOBAL_SHORTCUTS_DBUS_IFACE

#define INHIBIT_DBUS_IFACE DESKTOP_DBUS_IFACE ".Inhibit"
#define INHIBIT_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Inhibit"
#define INHIBIT_PERMISSION_TABLE "inhibit"
#define INHIBIT_PERMISSION_ID "inhibit"
#define INHIBIT_ENTITLEMENT_NAME INHIBIT_DBUS_IFACE

#define INPUT_CAPTURE_DBUS_IFACE DESKTOP_DBUS_IFACE ".InputCapture"
#define INPUT_CAPTURE_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".InputCapture"
#define INPUT_CAPTURE_PERMISSION_TABLE "input-capture"
#define INPUT_CAPTURE_PERMISSION_ID "input-capture"
#define INPUT_CAPTURE_ENTITLEMENT_NAME INPUT_CAPTURE_DBUS_IFACE

#define LOCATION_DBUS_IFACE DESKTOP_DBUS_IFACE ".Location"
#define LOCATION_PERMISSION_TABLE "location"
#define LOCATION_PERMISSION_ID "location"
#define LOCATION_ENTITLEMENT_NAME LOCATION_DBUS_IFACE

#define MEMORY_MONITOR_DBUS_IFACE DESKTOP_DBUS_IFACE ".MemoryMonitor"
#define MEMORY_MONITOR_ENTITLEMENT_NAME MEMORY_MONITOR_DBUS_IFACE

#define NETWORK_MONITOR_DBUS_IFACE DESKTOP_DBUS_IFACE ".NetworkMonitor"
#define NETWORK_MONITOR_ENTITLEMENT_NAME NETWORK_MONITOR_DBUS_IFACE

#define NOTIFICATION_DBUS_IFACE DESKTOP_DBUS_IFACE ".Notification"
#define NOTIFICATION_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Notification"
#define NOTIFICATION_PERMISSION_TABLE "notifications"
#define NOTIFICATION_PERMISSION_ID "notification"
#define NOTIFICATION_ENTITLEMENT_NAME NOTIFICATION_DBUS_IFACE

#define OPEN_URI_DBUS_IFACE DESKTOP_DBUS_IFACE ".OpenURI"
#define OPEN_URI_PERMISSION_TABLE "desktop-used-apps"
#define OPEN_URI_ENTITLEMENT_NAME OPEN_URI_DBUS_IFACE

#define POWER_PROFILE_MONITOR_DBUS_IFACE DESKTOP_DBUS_IFACE ".PowerProfileMonitor"
#define POWER_PROFILE_MONITOR_ENTITLEMENT_NAME POWER_PROFILE_MONITOR_DBUS_IFACE

#define PRINT_DBUS_IFACE DESKTOP_DBUS_IFACE ".Print"
#define PRINT_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Print"
#define PRINT_ENTITLEMENT_NAME PRINT_DBUS_IFACE

#define PROXY_RESOLVER_DBUS_IFACE DESKTOP_DBUS_IFACE ".ProxyResolver"
#define PROXY_RESOLVER_ENTITLEMENT_NAME PROXY_RESOLVER_DBUS_IFACE

#define REALTIME_DBUS_IFACE DESKTOP_DBUS_IFACE ".Realtime"
#define REALTIME_PERMISSION_TABLE "realtime"
#define REALTIME_PERMISSION_ID "realtime"
#define REALTIME_ENTITLEMENT_NAME REALTIME_DBUS_IFACE

#define REMOTE_DESKTOP_DBUS_IFACE DESKTOP_DBUS_IFACE ".RemoteDesktop"
#define REMOTE_DESKTOP_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".RemoteDesktop"
#define REMOTE_DESKTOP_PERMISSION_TABLE "remote-desktop"
#define REMOTE_DESKTOP_ENTITLEMENT_NAME REMOTE_DESKTOP_DBUS_IFACE

#define SCREEN_CAST_DBUS_IFACE DESKTOP_DBUS_IFACE ".ScreenCast"
#define SCREEN_CAST_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".ScreenCast"
#define SCREEN_CAST_PERMISSION_TABLE "screencast"
#define SCREEN_CAST_ENTITLEMENT_NAME SCREEN_CAST_DBUS_IFACE

#define SCREENSHOT_DBUS_IFACE DESKTOP_DBUS_IFACE ".Screenshot"
#define SCREENSHOT_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Screenshot"
#define SCREENSHOT_PERMISSION_TABLE "screenshot"
#define SCREENSHOT_PERMISSION_ID "screenshot"
#define SCREENSHOT_ENTITLEMENT_NAME SCREENSHOT_DBUS_IFACE

#define SECRET_DBUS_IFACE DESKTOP_DBUS_IFACE ".Secret"
#define SECRET_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Secret"
#define SECRET_ENTITLEMENT_NAME SECRET_DBUS_IFACE

#define SETTINGS_DBUS_IFACE DESKTOP_DBUS_IFACE ".Settings"
#define SETTINGS_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Settings"
#define SETTINGS_ENTITLEMENT_NAME SETTINGS_DBUS_IFACE

#define TRASH_DBUS_IFACE DESKTOP_DBUS_IFACE ".Trash"
#define TRASH_ENTITLEMENT_NAME TRASH_DBUS_IFACE

#define USB_DBUS_IFACE DESKTOP_DBUS_IFACE ".Usb"
#define USB_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Usb"
#define USB_PERMISSION_TABLE "usb"
#define USB_PERMISSION_ID "usb"
#define USB_ENTITLEMENT_NAME USB_DBUS_IFACE
#define USB_DEVICES_ENTITLEMENT_NAME USB_ENTITLEMENT_NAME ".Devices"

#define WALLPAPER_DBUS_IFACE DESKTOP_DBUS_IFACE ".Wallpaper"
#define WALLPAPER_DBUS_IMPL_IFACE DESKTOP_DBUS_IMPL_IFACE ".Wallpaper"
#define WALLPAPER_PERMISSION_TABLE "wallpaper"
#define WALLPAPER_PERMISSION_ID "wallpaper"
#define WALLPAPER_ENTITLEMENT_NAME WALLPAPER_DBUS_IFACE
