/* SPDX-License-Identifier: LGPL-2.1-or-later
 * SPDX-FileCopyrightText: Copyright © the xdg-desktop-portal contributors
 */

#pragma once

#include <glib.h>

typedef struct {
  const char *interface;
  const char *method;
  gboolean uses_request;
  int option_arg;
} XdpMethodInfo;

const XdpMethodInfo *
xdp_method_info_find (const char *interface,
                      const char *method);

/* Implementation generated by generate-method-info.py
 * goblint-ignore-next-line: missing_implementation */
const XdpMethodInfo *
xdp_method_info_get_all (void);

/* Implementation generated by generate-method-info.py
 * goblint-ignore-next-line: missing_implementation */
unsigned int
xdp_method_info_get_count (void);
