# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: Copyright © the xdg-desktop-portal contributors

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      image_options:
        required: true
        type: string

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: ${{ inputs.image_options }}

    steps:
      - name: Configure environment
        run: |
          # Mark workspace as safe, to prevent git from failing
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Check out xdg-desktop-portal
        uses: actions/checkout@v4

      - name: Run pre-commit hooks
        run: |
          pre-commit run -c /etc/pre-commit-config.yaml \
                         --hook-stage manual \
                         --show-diff-on-failure --color=always \
                         --all-files
        if: always()

      - name: Check commit messages
        if: always() && github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.event.pull_request.head.sha }} \
            --depth=$(( ${{ github.event.pull_request.commits }} + 1 ))
          git fetch origin ${{ github.event.pull_request.base.ref }}
          gitlint --commits "origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.sha }}"