# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: Copyright © the xdg-desktop-portal contributors

name: CI

on: [push, pull_request]

jobs:
  build-container:
    name: Build Container
    uses: ./.github/workflows/container.yml
    permissions:
      packages: write
    with:
      image: xdg-desktop-portal:2026-06-08.0
      containerfile: .github/workflows/Containerfile

  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    needs: build-container
    permissions:
      security-events: write
    with:
      image: ${{ needs.build-container.outputs.image }}
      image_options: ${{ needs.build-container.outputs.image_options }}

  pages:
    name: Documentation & Website
    uses: ./.github/workflows/pages.yml
    needs: build-container
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      image: ${{ needs.build-container.outputs.image }}
      image_options: ${{ needs.build-container.outputs.image_options }}